#!/bin/bash
DATE=$(date +%F)
LOGSDIR=/home/centos/shellscript-logs
SCRIPT_NAME=$0
LOGFILE=$LOGSDIR/$0/$DATE.log
USERID=$(id -u)
R="\e[31m"
N="\e[0m"

if [ $USERID -ne 0 ]
then
     echo -e "$R ERROR:pls run this script with root user $N"
     exit 1
fi

for i in $@
do
yum install $i -y
done